In [15]:
def get_nonzero_diag_product(X):
    non_zero_diag = np.diagonal(X)[np.diagonal(X) != 0]
    if non_zero_diag.size:
        return np.prod(non_zero_diag)
    return None

In [2]:
import numpy as np

In [20]:
get_nonzero_diag_product(np.array([[0, 0], [0, 0]]))

In [6]:
np.prod(np.array([]), initial = None)

ValueError: zero-size array to reduction operation multiply which has no identity

In [41]:
a = np.arange(6) - np.arange(6)[:, np.newaxis]
np.array((a > -3) & (a < 1), dtype =int)

array([[1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 1]])

In [60]:
def calc_expectations(h, w, X, Q):
    def sum_k_columns_matrix(size, k):
        a = np.arange(size) - np.arange(size)[:, np.newaxis]
        return np.array((a > -k) & (a < 1), dtype=int)
    sum_cols = sum_k_columns_matrix(Q.shape[1], w).T
    sum_rows = sum_k_columns_matrix(Q.shape[0], h)
    prob_Q = sum_rows.dot(Q).dot(sum_cols)
    return (prob_Q * X)


In [61]:
calc_expectations(2, 2, np.array([ [1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4] ]), np.array([ [0.2, 0, 0.3, 0.1], [0.1, 0, 0.2, 0], [0.05, 0, 0, 0], [0, 0, 0, 0.05] ]))

array([[0.2 , 0.2 , 0.3 , 0.4 ],
       [0.6 , 0.6 , 1.  , 1.2 ],
       [0.45, 0.45, 0.6 , 0.6 ],
       [0.2 , 0.2 , 0.  , 0.2 ]])

In [84]:
X = np.array([ [np.nan, 1, 2], [np.nan, 1, np.nan], [5, 6, 7] ])
def replace_nan_to_means(X):
    mean_cols = np.nanmean(X, axis = 0)
    inds = np.where(np.isnan(X))
    X_copy = X.copy()
    X_copy[inds] = mean_cols[inds[1]]
    return X_copy

In [87]:
print(replace_nan_to_means(X))
print(X)

[[5.  1.  2. ]
 [5.  1.  4.5]
 [5.  6.  7. ]]
[[nan  1.  2.]
 [nan  1. nan]
 [ 5.  6.  7.]]


In [130]:
def get_max_before_zero(x):
    import numpy as np
    diag_shift = np.diag(np.ones((x.size - 1)), 1)
    mask = np.array(x == 0, dtype=int).dot(diag_shift)
    mask = np.array(mask, dtype=bool)
    if x[mask].size:
        return x[mask].max()
    return None


In [134]:
x = np.array([1, 2, 0, -3, 0, 0])
get_max_before_zero(x)

0

In [27]:
x = np.array([0, 0, 1, 1, 1, 2, 1])
def encode_rle(x):
    import numpy as np
    x_shift = np.roll(x, 1)
    mask = x_shift != x
    mask[0] = True
    unique_num = x[mask]
    ind_start = np.where(mask)[0]
    ind_end = np.roll(ind_start, -1)
    ind_end[-1] = x.size 
    unique_len = ind_end - ind_start
    return (unique_num, unique_len)

type(encode_rle(x)[0])

numpy.ndarray